### ISSUE TITLE
Error with new projection system

### ISSUE THREAD

**Issue by Miclebrick** [Litote/kmongo#102]
```
[07:57:19 ERROR]: [SLCore] [ACF] Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `net.starlegacy.slcore.mongo.schema.nations.NationRelation$Level` out of START_OBJECT token
[07:57:19 ERROR]: [SLCore] [ACF]  at [Source: de.undercouch.bson4jackson.io.LittleEndianInputStream@3c35c4c8; pos: 0]
[07:57:19 ERROR]: [SLCore] [ACF]        at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:63)
[07:57:19 ERROR]: [SLCore] [ACF]        at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1343)
[07:57:19 ERROR]: [SLCore] [ACF]        at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1139)
[07:57:19 ERROR]: [SLCore] [ACF]        at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1093)
[07:57:19 ERROR]: [SLCore] [ACF]        at com.fasterxml.jackson.databind.deser.std.EnumDeserializer._deserializeOther(EnumDeserializer.java:267)
[07:57:19 ERROR]: [SLCore] [ACF]        at com.fasterxml.jackson.databind.deser.std.EnumDeserializer.deserialize(EnumDeserializer.java:206)
[07:57:19 ERROR]: [SLCore] [ACF]        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4013)
[07:57:19 ERROR]: [SLCore] [ACF]        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3091)
[07:57:19 ERROR]: [SLCore] [ACF]        at org.litote.kmongo.jackson.JacksonCodec.decode(JacksonCodec.kt:160)
[07:57:19 ERROR]: [SLCore] [ACF]        at net.starlegacy.slcore.mongo.schema.nations.NationRelation$Companion$getRelationWish$$inlined$projection$1.decode(Projections.kt:65)
[07:57:19 ERROR]: [SLCore] [ACF]        at net.starlegacy.slcore.mongo.schema.nations.NationRelation$Companion$getRelationWish$$inlined$projection$1.decode(Projections.kt:50)
[07:57:19 ERROR]: [SLCore] [ACF]        at com.mongodb.operation.CommandResultArrayCodec.decode(CommandResultArrayCodec.java:52)
[07:57:19 ERROR]: [SLCore] [ACF]        at com.mongodb.operation.CommandResultDocumentCodec.readValue(CommandResultDocumentCodec.java:60)
[07:57:19 ERROR]: [SLCore] [ACF]        at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:84)
[07:57:19 ERROR]: [SLCore] [ACF]        at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:41)
[07:57:19 ERROR]: [SLCore] [ACF]        at org.bson.codecs.configuration.LazyCodec.decode(LazyCodec.java:47)
[07:57:19 ERROR]: [SLCore] [ACF]        at org.bson.codecs.BsonDocumentCodec.readValue(BsonDocumentCodec.java:101)
[07:57:19 ERROR]: [SLCore] [ACF]        at com.mongodb.operation.CommandResultDocumentCodec.readValue(CommandResultDocumentCodec.java:63)
[07:57:19 ERROR]: [SLCore] [ACF]        at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:84)
[07:57:19 ERROR]: [SLCore] [ACF]        at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:41)
[07:57:19 ERROR]: [SLCore] [ACF]        at com.mongodb.internal.connection.ReplyMessage.<init>(ReplyMessage.java:51)
[07:57:19 ERROR]: [SLCore] [ACF]        at com.mongodb.internal.connection.InternalStreamConnection.getCommandResult(InternalStreamConnection.java:393)
[07:57:19 ERROR]: [SLCore] [ACF]        at com.mongodb.internal.connection.InternalStreamConnection.receiveCommandMessageResponse(InternalStreamConnection.java:299)
[07:57:19 ERROR]: [SLCore] [ACF]        at com.mongodb.internal.connection.InternalStreamConnection.sendAndReceive(InternalStreamConnection.java:255)
[07:57:19 ERROR]: [SLCore] [ACF]        at com.mongodb.internal.connection.UsageTrackingInternalConnection.sendAndReceive(UsageTrackingInternalConnection.java:99)
[07:57:19 ERROR]: [SLCore] [ACF]        at com.mongodb.internal.connection.DefaultConnectionPool$PooledConnection.sendAndReceive(DefaultConnectionPool.java:444)
[07:57:19 ERROR]: [SLCore] [ACF]        at com.mongodb.internal.connection.CommandProtocolImpl.execute(CommandProtocolImpl.java:72)
[07:57:19 ERROR]: [SLCore] [ACF]        at com.mongodb.internal.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:200)
[07:57:19 ERROR]: [SLCore] [ACF]        at com.mongodb.internal.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:269)
[07:57:19 ERROR]: [SLCore] [ACF]        at com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:131)
[07:57:19 ERROR]: [SLCore] [ACF]        at com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:123)
[07:57:19 ERROR]: [SLCore] [ACF]        at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:242)
[07:57:19 ERROR]: [SLCore] [ACF]        at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:233)
[07:57:19 ERROR]: [SLCore] [ACF]        at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:136)
[07:57:19 ERROR]: [SLCore] [ACF]        at com.mongodb.operation.FindOperation$1.call(FindOperation.java:702)
[07:57:19 ERROR]: [SLCore] [ACF]        at com.mongodb.operation.FindOperation$1.call(FindOperation.java:696)
[07:57:19 ERROR]: [SLCore] [ACF]        at com.mongodb.operation.OperationHelper.withConnectionSource(OperationHelper.java:462)
[07:57:19 ERROR]: [SLCore] [ACF]        at com.mongodb.operation.OperationHelper.withConnection(OperationHelper.java:406)
[07:57:19 ERROR]: [SLCore] [ACF]        at com.mongodb.operation.FindOperation.execute(FindOperation.java:696)
[07:57:19 ERROR]: [SLCore] [ACF]        at com.mongodb.operation.FindOperation.execute(FindOperation.java:83)
[07:57:19 ERROR]: [SLCore] [ACF]        at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:179)
[07:57:19 ERROR]: [SLCore] [ACF]        at com.mongodb.client.internal.FindIterableImpl.first(FindIterableImpl.java:199)
[07:57:19 ERROR]: [SLCore] [ACF]        at com.mongodb.client.internal.MappingIterable.first(MappingIterable.java:45)
[07:57:19 ERROR]: [SLCore] [ACF]        at kotlin.collections.KMongoIterableKt.firstOrNull(KMongoIterable.kt:67)         
[07:57:19 ERROR]: [SLCore] [ACF]        at net.starlegacy.slcore.mongo.schema.nations.NationRelation$Companion.getRelationWish(NationRelation.kt:47)
[07:57:19 ERROR]: [SLCore] [ACF]        at net.starlegacy.slcore.mongo.schema.nations.NationRelation$Companion$changeRelationWish$1.invoke(NationRelation.kt:65)
[07:57:19 ERROR]: [SLCore] [ACF]        at net.starlegacy.slcore.mongo.schema.nations.NationRelation$Companion$changeRelationWish$1.invoke(NationRelation.kt:29)
[07:57:19 ERROR]: [SLCore] [ACF]        at net.starlegacy.slcore.mongo.MongoManagerKt.session(MongoManager.kt:64)     
[07:57:19 ERROR]: [SLCore] [ACF]        at net.starlegacy.slcore.mongo.schema.nations.NationRelation$Companion.changeRelationWish(NationRelation.kt:50)
[07:57:19 ERROR]: [SLCore] [ACF]        at net.starlegacy.slcore.mongo.IMPORTKt$importToMongo$1.invoke(IMPORT.kt:456)
[07:57:19 ERROR]: [SLCore] [ACF]        at net.starlegacy.slcore.mongo.IMPORTKt$importToMongo$1.invoke(IMPORT.kt)
[07:57:19 ERROR]: [SLCore] [ACF]        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:104)
[07:57:19 ERROR]: [SLCore] [ACF]        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:75)
[07:57:19 ERROR]: [SLCore] [ACF]        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:58)
[07:57:19 ERROR]: [SLCore] [ACF]        at net.starlegacy.slcore.database.DatabaseManager.sql(DatabaseManager.kt:152)             
[07:57:19 ERROR]: [SLCore] [ACF]        at net.starlegacy.slcore.database.DatabaseManager.sql$default(DatabaseManager.kt:142)
[07:57:19 ERROR]: [SLCore] [ACF]        at net.starlegacy.slcore.mongo.IMPORTKt.importToMongo(IMPORT.kt:59)         
[07:57:19 ERROR]: [SLCore] [ACF]        at net.starlegacy.slcore.command.SLCoreDebugCommand.onMongo(SLDebugCommand.kt:36)
[07:57:19 ERROR]: [SLCore] [ACF]        ... 17 more        
```

code:
```Kotlin
        fun getRelationWish(nation: Id<Nation>, other: Id<Nation>): Level = when (nation) {
            other -> Level.NATION
            else -> col.projection(
                NationRelation::wish,
                and(NationRelation::nation eq nation, NationRelation::other eq other)
            ).firstOrNull() ?: Level.NONE
        }
```

**Comment by zigzago** [comment]
Thanks for reporting. It is fixed now. https://github.com/Litote/kmongo/commit/2cca25a843a9782eb55b3fad1343902bf046304a
