### ISSUE TITLE
Graal compatibility. Kmongo uses incompatible methods.

### ISSUE THREAD

**Issue by soberich** [Litote/kmongo#131]
given we use `Kmongo`

when execute `native-image ...`

have this 
```console
Detailed message:
Error: No instances are allowed in the image heap for a class that is initialized or reinitialized at image runtime: sun.security.provider.NativePRNG
Trace: 	object java.security.SecureRandom
	object sun.security.ssl.SSLContextImpl$DefaultSSLContext
	object sun.security.ssl.SSLSocketFactoryImpl
	method com.mongodb.MongoClientOptions.getSocketFactory()
Call path from entry point to com.mongodb.MongoClientOptions.getSocketFactory(): 
	at com.mongodb.MongoClientOptions.getSocketFactory(MongoClientOptions.java:694)
	at com.mongodb.Mongo.createCluster(Mongo.java:736)
	at com.mongodb.Mongo.createCluster(Mongo.java:722)
	at com.mongodb.Mongo.<init>(Mongo.java:291)
	at com.mongodb.Mongo.<init>(Mongo.java:286)
	at com.mongodb.Mongo.<init>(Mongo.java:282)
	at com.mongodb.MongoClient.<init>(MongoClient.java:180)
	at org.litote.kmongo.KMongo.createClient(KMongo.kt:109)
	at org.litote.kmongo.KMongo.createClient(KMongo.kt:85)
	at org.litote.kmongo.KMongo.createClient(KMongo.kt:40)
	at com.bol.graal.config.DatabaseConfig.db(DatabaseConfig.kt:22)
	at com.bol.graal.config.$DatabaseConfigDefinition$$exec1.invokeInternal(Unknown Source)
	at io.micronaut.context.AbstractExecutableMethod.invoke(AbstractExecutableMethod.java:144)
	at io.micronaut.scheduling.processor.ScheduledMethodProcessor.lambda$process$5(ScheduledMethodProcessor.java:110)
	at io.micronaut.scheduling.processor.ScheduledMethodProcessor$$Lambda$870/1302298593.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:748)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:473)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
	at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0)
Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Detected a direct/mapped ByteBuffer in the image heap. A direct ByteBuffer has a pointer to unmanaged C memory, and C memory from the image generator is not available at image run time. A mapped ByteBuffer references a file descriptor, which is no longer open and mapped at run time. The object was probably created by a class initializer and is reachable from a static field. By default, all class initialization is done during native image building.You can manually delay class initialization to image run time by using the option --delay-class-initialization-to-runtime=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
```

**Comment by zigzago** [comment]
This is not a KMongo issue: see https://github.com/oracle/graal/issues/712
