### ISSUE TITLE
Kmongo init error

### ISSUE THREAD

**Issue by Dkhusainov** [Litote/kmongo#14]
Exception in thread "main" java.lang.VerifyError: Bad type on operand stack
Exception Details:
 Location:
    kotlin/reflect/jvm/internal/ReflectionFactoryImpl.function(Lkotlin/jvm/internal/FunctionReference;)Lkotlin/reflect/KFunction; @5: invokestatic
  Reason:
    Type 'kotlin/jvm/internal/FunctionReference' (current frame, stack[2]) is not assignable to 'kotlin/jvm/internal/CallableReference'
  Current Frame:
    bci: @5
    flags: { }
    locals: { 'kotlin/reflect/jvm/internal/ReflectionFactoryImpl', 'kotlin/jvm/internal/FunctionReference' }
    stack: { uninitialized 0, uninitialized 0, 'kotlin/jvm/internal/FunctionReference' }
  Bytecode:
    0x0000000: bb00 3b59 2bb8 0053 2bb6 0059 2bb6 005c
    0x0000010: 2bb6 0060 b700 63b0

	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at kotlin.jvm.internal.Reflection.<clinit>(Reflection.java:32)
	at org.litote.kmongo.util.KMongoConfiguration.<clinit>(KMongoConfiguration.kt)
	at org.litote.kmongo.KMongo.configureRegistry(KMongo.kt:218)
	at org.litote.kmongo.KMongo.configureOptions(KMongo.kt:215)
	at org.litote.kmongo.KMongo.createClient(KMongo.kt:104)
	at org.litote.kmongo.KMongo.createClient(KMongo.kt:80)
	at org.litote.kmongo.KMongo.createClient(KMongo.kt:50)

This issue only happens only when I run the app from jar, it works fine in the IDE. My Kotlin version is 1.1.1

**Comment by zigzago** [comment]
It looks like a classpath issue.
Try to force the kotlin version in you build tool. For example, in maven:

``` xml
<dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.jetbrains.kotlin</groupId>
                <artifactId>kotlin-stdlib</artifactId>
                <version>1.1.1</version>
            </dependency>
            <dependency>
                <groupId>org.jetbrains.kotlin</groupId>
                <artifactId>kotlin-reflect</artifactId>
                <version>1.1.1</version>
            </dependency>
</dependencyManagement>
```

**Comment by Dkhusainov** [comment]
_kotlin-reflect_ did it for me. 

They should probably give a propper exception instead of this gibberish... Issue can be closed, thanks for help.
