### ISSUE TITLE
Error while writing to the database

### ISSUE THREAD

**Issue by k1ll1n** [Litote/kmongo#160]
```
Caused by: com.fasterxml.jackson.databind.JsonMappingException: state should be: w is an Integer (through reference chain: app.Book["uri"]->com.mongodb.MongoClientURI["options"]->com.mongodb.MongoClientOptions["writeConcern"]->com.mongodb.WriteConcern["w"])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:394)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:353)
	at com.fasterxml.jackson.databind.ser.std.StdSerializer.wrapAndThrow(StdSerializer.java:316)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:730)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:166)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:727)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:722)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:166)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:727)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:722)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:166)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:727)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:722)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:166)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
	at com.fasterxml.jackson.databind.ObjectMapper._configAndWriteValue(ObjectMapper.java:4094)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsBytes(ObjectMapper.java:3428)
	at org.litote.kmongo.jackson.JacksonCodec.encode(JacksonCodec.kt:186)
	... 34 more
Caused by: java.lang.IllegalStateException: state should be: w is an Integer
	at com.mongodb.assertions.Assertions.isTrue(Assertions.java:70)
	at com.mongodb.WriteConcern.getW(WriteConcern.java:349)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:688)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:722)
	... 49 more
```

```
data class Book(val test: String) {
    val dbUrl = "mongodb+srv://login:password@test-setyp.mongodb.net/test?retryWrites=true&w=majority"

    val uri = MongoClientURI(dbUrl)
    val client = KMongo.createClient(uri)
    val db = client.getDatabase("test")
    val col = db.getCollection<Book>()

    fun  insert() {
        col.insertOne(Book("test2"))
    }
}
```

If I do a reading from the database, then this works without problems.

**Comment by zigzago** [comment]
This is not a bug. You try to serialize a Book object, that contains an uri property of MongoClientURI type. And there is no Serializer/deserializer for the MongoClientURI type.

Try this code:


```kotlin
fun main() {

val dbUrl = "mongodb+srv://login:password@test-setyp.mongodb.net/test?retryWrites=true&w=majority"
val uri = MongoClientURI(dbUrl)
val client = KMongo.createClient(uri)
val db = client.getDatabase("test")
val col = db.getCollection<Book>()

col.insertOne(Book("test2"))
}

data class Book(val test: String) 
```

HTH
