### ISSUE TITLE
NoSuchMethodError: kotlinx.serialization.json.JsonConfiguration.copy

### ISSUE THREAD

**Issue by Lab9** [Litote/kmongo#189]
I'm trying to create a test rest api with ktor and would like to use kmongo with the kotlinx.serialization engine.

`build.gradle`:
```gradle
buildscript {
    repositories {
        jcenter()
    }
    
    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

apply plugin: 'kotlin'
apply plugin: 'application'

group 'com.example'
version '0.0.1'
mainClassName = "io.ktor.server.netty.EngineMain"

sourceSets {
    main.kotlin.srcDirs = main.java.srcDirs = ['src']
    test.kotlin.srcDirs = test.java.srcDirs = ['test']
    main.resources.srcDirs = ['resources']
    test.resources.srcDirs = ['testresources']
}

repositories {
    mavenLocal()
    jcenter()
    maven { url 'https://kotlin.bintray.com/ktor' }
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:$kotlin_version"
    implementation "io.ktor:ktor-server-netty:$ktor_version"
    implementation "ch.qos.logback:logback-classic:$logback_version"
    implementation "io.ktor:ktor-server-core:$ktor_version"
    implementation "io.ktor:ktor-serialization:$ktor_version"
    testImplementation "io.ktor:ktor-server-tests:$ktor_version"

    implementation "org.litote.kmongo:kmongo-serialization:$kmongo_version"  // 3.12.2 --> specified in gradle.properties
}
```
And
`Application.kt`:
```kotlin
import io.ktor.application.Application
import io.ktor.application.install
import io.ktor.features.CORS
import io.ktor.features.CallLogging
import io.ktor.features.ContentNegotiation
import io.ktor.serialization.serialization

fun main(args: Array<String>): Unit = io.ktor.server.netty.EngineMain.main(args)

@Suppress("unused") // Referenced in application.conf
@kotlin.jvm.JvmOverloads
fun Application.module(testing: Boolean = false) {
    install(CallLogging)
    install(CORS)
    install(ContentNegotiation) {
        serialization()
    }
}
```

Throws the following exception:
```exception
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97)
	at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Static.call(CallerImpl.kt:106)
	at kotlin.reflect.jvm.internal.KCallableImpl.callDefaultMethod$kotlin_reflection(KCallableImpl.kt:166)
	at kotlin.reflect.jvm.internal.KCallableImpl.callBy(KCallableImpl.kt:110)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.callFunctionWithInjection(ApplicationEngineEnvironmentReloading.kt:392)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.executeModuleFunction(ApplicationEngineEnvironmentReloading.kt:340)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.access$executeModuleFunction(ApplicationEngineEnvironmentReloading.kt:33)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading$instantiateAndConfigureApplication$1$$special$$inlined$forEach$lambda$1.invoke(ApplicationEngineEnvironmentReloading.kt:287)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading$instantiateAndConfigureApplication$1$$special$$inlined$forEach$lambda$1.invoke(ApplicationEngineEnvironmentReloading.kt:33)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.avoidingDoubleStartupFor(ApplicationEngineEnvironmentReloading.kt:320)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.access$avoidingDoubleStartupFor(ApplicationEngineEnvironmentReloading.kt:33)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading$instantiateAndConfigureApplication$1.invoke(ApplicationEngineEnvironmentReloading.kt:286)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading$instantiateAndConfigureApplication$1.invoke(ApplicationEngineEnvironmentReloading.kt:33)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.avoidingDoubleStartup(ApplicationEngineEnvironmentReloading.kt:302)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.instantiateAndConfigureApplication(ApplicationEngineEnvironmentReloading.kt:284)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.createApplication(ApplicationEngineEnvironmentReloading.kt:137)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.start(ApplicationEngineEnvironmentReloading.kt:257)
	at io.ktor.server.netty.NettyApplicationEngine.start(NettyApplicationEngine.kt:126)
	at io.ktor.server.netty.EngineMain.main(EngineMain.kt:26)
	at com.example.ApplicationKt.main(Application.kt:14)
Caused by: java.lang.NoSuchMethodError: kotlinx.serialization.json.JsonConfiguration.copy$default(Lkotlinx/serialization/json/JsonConfiguration;ZZZZZLjava/lang/String;ZLjava/lang/String;Lkotlinx/serialization/UpdateMode;ILjava/lang/Object;)Lkotlinx/serialization/json/JsonConfiguration;
	at io.ktor.serialization.SerializationConverterKt.<clinit>(SerializationConverter.kt:82)
	at com.example.ApplicationKt$module$3.invoke(Application.kt:34)
	at com.example.ApplicationKt$module$3.invoke(Application.kt)
	at io.ktor.features.ContentNegotiation$Feature.install(ContentNegotiation.kt:101)
	at io.ktor.features.ContentNegotiation$Feature.install(ContentNegotiation.kt:94)
	at io.ktor.application.ApplicationFeatureKt.install(ApplicationFeature.kt:64)
	at com.example.ApplicationKt.module(Application.kt:33)
	at com.example.ApplicationKt.module$default(Application.kt:18)
	... 24 more

Process finished with exit code 1
```

Removing 
```gradle
implementation "org.litote.kmongo:kmongo-serialization:$kmongo_version"
```
from the `build.gradle` seems to fix it but that's kind of not my intention...

Any suggestions on how to fix this? I'm happy to provide any necessary information to fix the issue.

**Comment by zigzago** [comment]
@Lab9 Looks like a dependency issue. Please check what is the kotlinx-serialization-runtime dependency version. KMongo 3.12.2 needs kotlinx-serialization-runtime  0.20.0 (and kotlin 1.3.70). 

I suspect ktor-serialization uses an other version.

HTH
