### ISSUE TITLE
BsonInvalidOperationException when using newId()

### ISSUE THREAD

**Issue by nidomiro** [Litote/kmongo#195]
I'm trying to write a test for my Repository where I'm saving a value directly to the db and want to retrieve it by it's id via my Repository.

This Test fails with the following exception:

```
org.bson.BsonInvalidOperationException: readObjectId can only be called when CurrentBSONType is OBJECT_ID, not when CurrentBSONType is STRING.

	at org.bson.AbstractBsonReader.verifyBSONType(AbstractBsonReader.java:690)
	at org.bson.AbstractBsonReader.checkPreconditions(AbstractBsonReader.java:722)
	at org.bson.AbstractBsonReader.readObjectId(AbstractBsonReader.java:422)
	at org.litote.kmongo.jackson.JacksonCodec.encode(JacksonCodec.kt:196)
	at com.mongodb.client.model.BuildersHelper.encodeValue(BuildersHelper.java:37)
	at com.mongodb.client.model.Filters$SimpleEncodingFilter.toBsonDocument(Filters.java:1175)
	at com.mongodb.internal.operation.Operations.createFindOperation(Operations.java:133)
	at com.mongodb.internal.operation.Operations.findFirst(Operations.java:116)
	at com.mongodb.internal.operation.AsyncOperations.findFirst(AsyncOperations.java:99)
	at com.mongodb.internal.async.client.AsyncFindIterableImpl.first(AsyncFindIterableImpl.java:183)
	at com.mongodb.reactivestreams.client.internal.SingleResultCallbackSubscription.requestInitialData(SingleResultCallbackSubscription.java:39)
	at com.mongodb.reactivestreams.client.internal.AbstractSubscription.tryRequestInitialData(AbstractSubscription.java:174)
	at com.mongodb.reactivestreams.client.internal.AbstractSubscription.request(AbstractSubscription.java:97)
	at kotlinx.coroutines.reactive.AwaitKt$awaitOne$$inlined$suspendCancellableCoroutine$lambda$1.onSubscribe(Await.kt:105)
	at com.mongodb.reactivestreams.client.internal.SingleResultCallbackSubscription.<init>(SingleResultCallbackSubscription.java:34)
	at com.mongodb.reactivestreams.client.internal.Publishers.lambda$publish$1(Publishers.java:69)
	at kotlinx.coroutines.reactive.AwaitKt.awaitOne(Await.kt:97)
	at kotlinx.coroutines.reactive.AwaitKt.awaitOne$default(Await.kt:95)
	at kotlinx.coroutines.reactive.AwaitKt.awaitFirstOrNull(Await.kt:46)
	at org.litote.kmongo.coroutine.CoroutineFindPublisher.first(CoroutineFindPublisher.kt:45)
	at org.litote.kmongo.coroutine.CoroutineCollection.findOne(CoroutineCollection.kt:1061)
	at org.litote.kmongo.coroutine.CoroutineCollection.findOneById(CoroutineCollection.kt:1085)
	at task.TaskEntityRepositoryImpl.getById(TaskEntityRepositoryImpl.kt:14)
	at task.TaskEntityRepositoryImplTest$getById$1.invokeSuspend(TaskEntityRepositoryImplTest.kt:60)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:272)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:79)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:54)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:36)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at BaseTest.runBlockingWithEmptyDb(BaseTest.kt:28)
	at task.TaskEntityRepositoryImplTest.getById(TaskEntityRepositoryImplTest.kt:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:686)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:205)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:201)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:137)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:71)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:135)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:248)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$5(DefaultLauncher.java:211)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:226)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:199)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:132)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
```

Test Code:
```kotlin
val col = database.getCollection<TaskEntity>(TaskEntity.collectionName)
val task1 = TaskEntity(
    id = newId(),
    name = "Task1",
    description = ""
)
val result = col.insertOne(task1)

val service = TaskEntityRepositoryImpl(database)
assertThat(service.getById(task1.id)).isEqualTo(task1)

```

Repository:
```kotlin
class TaskEntityRepositoryImpl(private val database: CoroutineDatabase) : TaskEntityRepository {

[...]

    override suspend fun getById(id: Id<TaskEntity>): TaskEntity? {
        return taskCollection.findOneById(id)
    }

[...]

    private val taskCollection: CoroutineCollection<TaskEntity>
        get() = database.getCollection(TaskEntity.collectionName)
}
```

**Comment by zigzago** [comment]
@nidomiro could you provide the TaskEntity definition ?

**Comment by nidomiro** [comment]
Of course :)
```kotlin
data class TaskEntity(
    @BsonId
    override val id: Id<TaskEntity>,

    val name: String,
    val description: String,
    val beginDate: Instant? = null,
    val dueDate: Instant? = null,
    val place: String? = null,

    val creationDate: Instant = Instant.now(),
    val modifyDate: Instant = creationDate

) : HasId<TaskEntity> {
    companion object {
        const val collectionName = "Tasks"
    }
}
```

**Comment by nidomiro** [comment]
I think the Id is not saved as ObjectId but as String.

Dumping the object via the bsonMapper and converting it to Json:
```kotlin
KMongoConfiguration.bsonMapper.writeValue(File("task1.bson"), task1)
```

```json
{"_id":"5e9c6e4acc5aa00092ce00da","name":"Task1","description":"","beginDate":null,"dueDate":null,"place":null,"creationDate":1587310154780,"modifyDate":1587310154780}
```

Looking into the db confirms my suspicion:
The fist one is created by KMongo, the second one via mongodb-query:
```
db.getCollection("Tasks").insertOne({
    "beginDate": null,
    "creationDate": 1587310154780,
    "description": "",
    "dueDate": null,
    "modifyDate": 1587310154780,
    "name": "Task1",
    "place": null
})
```

```json
[
  {
    "_id": "5e9c70e9d66fb107bb36c5f1",
    "beginDate": null,
    "creationDate": {"$date": "2020-04-19T15:40:25.469Z"},
    "description": "",
    "dueDate": null,
    "modifyDate": {"$date": "2020-04-19T15:40:25.469Z"},
    "name": "Task1",
    "place": null
  },
  {
    "_id": {"$oid": "5e9c71725956a5389dc1a89d"},
    "beginDate": null,
    "creationDate": 1587310154780,
    "description": "",
    "dueDate": null,
    "modifyDate": 1587310154780,
    "name": "Task1",
    "place": null
  }
]
```

**Comment by zigzago** [comment]
I add an unit test (https://github.com/Litote/kmongo/commit/e611fadab509cb1e8a09791d5318b4bc8107b92a) that is successful.

I suspect the issue may come from you HasId interface or class. Could you share it also ?

**Comment by nidomiro** [comment]
I found the error, it was my mistake...
I read https://litote.org/kmongo/object-mapping/#id-json-jackson-serialization the wrong way and thought I have to add it to KMongo like:  `KMongoConfiguration.registerBsonModule(IdJacksonModule())`

If I remove this line from the Constructor, the test is green.

Thanks for your time.
