### ISSUE TITLE
ExceptionInInitializerError

### ISSUE THREAD

**Issue by archyjs** [Litote/kmongo#216]
I'm not sure, if this is user-error oriented.. 

But.. I've followed the website guidelines..

I can't seem to figure this error out.

Stacktrace:
java.lang.ExceptionInInitializerError: null
	at org.litote.kmongo.reactivestreams.KMongo.createClient(KMongo.kt:44) ~[?:?]
	at org.litote.kmongo.reactivestreams.KMongo.createClient(KMongo.kt:66) ~[?:?]
	at org.litote.kmongo.reactivestreams.KMongo.createClient(KMongo.kt:35) ~[?:?]
	at git.archyjs.Qube.onEnable(Qube.kt:34) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.1.jar:git-Paper-91]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.1.jar:git-Paper-91]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.1.jar:git-Paper-91]
	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin(CraftServer.java:500) ~[patched_1.16.1.jar:git-Paper-91]
	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugins(CraftServer.java:414) ~[patched_1.16.1.jar:git-Paper-91]
	at net.minecraft.server.v1_16_R1.MinecraftServer.loadWorld(MinecraftServer.java:471) ~[patched_1.16.1.jar:git-Paper-91]
	at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:241) ~[patched_1.16.1.jar:git-Paper-91]
	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:940) ~[patched_1.16.1.jar:git-Paper-91]
	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-91]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.lang.IllegalStateException: Service ClassMappingTypeService not found
	at org.litote.kmongo.service.ClassMappingTypeKt$defaultService$2.invoke(ClassMappingType.kt:38) ~[?:?]
	at org.litote.kmongo.service.ClassMappingTypeKt$defaultService$2.invoke(ClassMappingType.kt) ~[?:?]
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74) ~[?:?]
	at org.litote.kmongo.service.ClassMappingTypeKt.getDefaultService(ClassMappingType.kt) ~[?:?]
	at org.litote.kmongo.service.ClassMappingTypeKt.getCurrentService(ClassMappingType.kt:50) ~[?:?]
	at org.litote.kmongo.service.ClassMappingTypeKt.access$getCurrentService$p(ClassMappingType.kt:1) ~[?:?]
	at org.litote.kmongo.service.ClassMappingType.<init>(ClassMappingType.kt:58) ~[?:?]
	at org.litote.kmongo.service.ClassMappingType.<clinit>(ClassMappingType.kt:58) ~[?:?]
	... 14 more

**Comment by zigzago** [comment]
Do you use an uberjar for you app ? Looks like this kind of file is not present in your classpath: https://github.com/Litote/kmongo/blob/master/kmongo-jackson-mapping/src/main/resources/META-INF/services/org.litote.kmongo.service.ClassMappingTypeService

**Comment by archyjs** [comment]
I solved it thanks to a system property set thanks though!

**Comment by Cormanz** [comment]
> I solved it thanks to a system property set thanks though!

Do you mind posting how you fixed this? I'm having the same problem a year and a half later.
