### ISSUE TITLE
findOne() with custom serialization throws BsonSerializationException

### ISSUE THREAD

**Issue by xiaodongw** [Litote/kmongo#230]
I have some code looks like this:
```kotlin
// ID for all resources
class ResourceId(...)

// Serializer & Deserializer for ResourceId
class ResourceIdSerializer : StdSerializer<ResourceId>(ResourceId::class.java) {
  override fun serialize(value: ResourceId, gen: JsonGenerator, serializers: SerializerProvider) {
    gen.writeString(value.toBase64())
  }
}
class ResourceIdDeserializer : StdDeserializer<ResourceId>(ResourceId::class.java) {
  override fun deserialize(p: JsonParser, ctxt: DeserializationContext): ResourceId {
    val str = p.valueAsString
    return ResourceId.fromBase64(str)
  }
}

// Data class
data class UserRow(
  /** User ID, unique */
  @BsonId val id: ResourceId,
  /** User handle (username), unique */
  @JsonProperty("h") val handle: String,
  /** User email */
  @JsonProperty("e") val email: String,
  /** Hash of the user password */
  @JsonProperty("p") val passwordHash: ByteString
)

// these works well
coll.insertOne(user)
coll.findOne(UserRow::email eq email)

// these throws BsonSerializationException
coll.findOne(UserRow::id eq id)
coll.findOneById(id)
```

This is the stacktrace.
```
Expected size to be 6400, not 5.
org.bson.BsonSerializationException: Expected size to be 6400, not 5.
	at org.bson.BsonBinaryReader$Context.popContext(BsonBinaryReader.java:428)
	at org.bson.BsonBinaryReader.doReadEndDocument(BsonBinaryReader.java:285)
	at org.bson.AbstractBsonReader.readEndDocument(AbstractBsonReader.java:358)
	at org.bson.AbstractBsonWriter.pipeDocument(AbstractBsonWriter.java:808)
	at org.bson.AbstractBsonWriter.pipe(AbstractBsonWriter.java:758)
	at org.bson.codecs.RawBsonDocumentCodec.encode(RawBsonDocumentCodec.java:45)
	at org.bson.codecs.RawBsonDocumentCodec.encode(RawBsonDocumentCodec.java:33)
	at org.litote.kmongo.jackson.JacksonCodec.encode(JacksonCodec.kt:188)
	at com.mongodb.client.model.BuildersHelper.encodeValue(BuildersHelper.java:37)
	at com.mongodb.client.model.Filters$SimpleEncodingFilter.toBsonDocument(Filters.java:1175)
	at com.mongodb.internal.operation.Operations.createFindOperation(Operations.java:133)
	at com.mongodb.internal.operation.Operations.findFirst(Operations.java:116)
	at com.mongodb.internal.operation.AsyncOperations.findFirst(AsyncOperations.java:99)
	at com.mongodb.internal.async.client.AsyncFindIterableImpl.first(AsyncFindIterableImpl.java:190)
	at com.mongodb.reactivestreams.client.internal.SingleResultCallbackSubscription.requestInitialData(SingleResultCallbackSubscription.java:39)
	at com.mongodb.reactivestreams.client.internal.AbstractSubscription.tryRequestInitialData(AbstractSubscription.java:177)
	at com.mongodb.reactivestreams.client.internal.AbstractSubscription.request(AbstractSubscription.java:100)
	at kotlinx.coroutines.reactive.AwaitKt$awaitOne$$inlined$suspendCancellableCoroutine$lambda$1.onSubscribe(Await.kt:105)
	at com.mongodb.reactivestreams.client.internal.SingleResultCallbackSubscription.<init>(SingleResultCallbackSubscription.java:34)
	at com.mongodb.reactivestreams.client.internal.Publishers.lambda$publish$1(Publishers.java:69)
	at kotlinx.coroutines.reactive.AwaitKt.awaitOne(Await.kt:97)
	at kotlinx.coroutines.reactive.AwaitKt.awaitOne$default(Await.kt:95)
	at kotlinx.coroutines.reactive.AwaitKt.awaitFirstOrNull(Await.kt:46)
	at org.litote.kmongo.coroutine.CoroutineFindPublisher.first(CoroutineFindPublisher.kt:45)
	at org.litote.kmongo.coroutine.CoroutineCollection.findOne(CoroutineCollection.kt:1061)
	at org.litote.kmongo.coroutine.CoroutineCollection.findOneById(CoroutineCollection.kt:1085)
	at leap.account.store.UserStoreImpl.readUser(UserStoreImpl.kt:36)
```

**Comment by xiaodongw** [comment]
After debugging and trying different ways, I found this fixes the problem:
```kotlin
class ResourceIdSerializer : StdSerializer<ResourceId>(ResourceId::class.java) {
  override fun serialize(value: ResourceId, gen: JsonGenerator, serializers: SerializerProvider) {
    gen.writeString(value.toBase64())
  }

  override fun acceptJsonFormatVisitor(visitor: JsonFormatVisitorWrapper, typeHint: JavaType?) {
    visitor.expectStringFormat(typeHint)
  }
}
```
Closing the issue.
