### ISSUE TITLE
A floating point number with all zeros after the point cannot be deserialized as Double or Float

### ISSUE THREAD

**Issue by lamba92** [Litote/kmongo#232]
I have a collection where the property `price` is a `kotlin.Float`. By chance one document has `"price": 2.0"` and when inserted in the database, MongoDB shows the value correctly as double but the JSON returned has `"price: 2"`. When deserializing that exact document the runtime throws:
```text
org.bson.BsonInvalidOperationException: readDouble can only be called when CurrentBSONType is DOUBLE, not when CurrentBSONType is INT32.
	at org.bson.AbstractBsonReader.verifyBSONType(AbstractBsonReader.java:690)
	at org.bson.AbstractBsonReader.checkPreconditions(AbstractBsonReader.java:722)
	at org.bson.AbstractBsonReader.readDouble(AbstractBsonReader.java:317)
	at com.github.jershell.kbson.FlexibleDecoder.decodeFloat(BsonFlexibleDecoder.kt:101)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeFloatElement(AbstractDecoder.kt:53)
	at it.belabs.beristo.data.food.Menu$Section$Course$AdditionalIngredient$$serializer.deserialize(Menu.kt)
	at it.belabs.beristo.data.food.Menu$Section$Course$AdditionalIngredient$$serializer.deserialize(Menu.kt:36)
```
Somehow the `price` of that document has been interpreted by the library as an `INT32` of some sort due to the `.0` missing from the MongoDB BSON deserialization. I was not able to find any workaround aside from storing `price` as `String` and manage that stuff at runtime, which is awful to say the least.

Not sure if it's a MongoDB Java library issue or a KMongo one tho.

**Comment by zigzago** [comment]
I do not reproduce the bug in unit test - see https://github.com/Litote/kmongo/commit/b993b68fb5ed1b8ca10344461b7823fff2a495f0

**Comment by lamba92** [comment]
I forgot to mention that i was using Kotlinx.serialization

**Comment by zigzago** [comment]
Ok but it works also with kotlinx. serialization with my unit test https://github.com/Litote/kmongo/blob/master/kmongo-core-tests/src/main/kotlin/org/litote/kmongo/issues/Issue232FloatSerialization.kt

**Comment by lamba92** [comment]
Turns out it was the IntelliJ MongoDB console/driver that converted the item to `INT32` when inserting it. When using KMongo to insert the item it is correctly stored as Float/Double.
