### ISSUE TITLE
java.lang.NoSuchMethodError when calling .toList() on CoroutinePublisher

### ISSUE THREAD

**Issue by alexanderfinn** [Litote/kmongo#239]
When I try to get a list of items from collection.find() method on a CoroutineCollection instance, I'm getting an exception:
```
Exception in thread "scheduledTasks" java.lang.NoSuchMethodError: kotlinx.coroutines.channels.LinkedListChannel: method 'void <init>()' not found
backend_1         | 	at kotlinx.coroutines.reactive.SubscriptionChannel.<init>(Channel.kt:51)
backend_1         | 	at kotlinx.coroutines.reactive.ChannelKt.openSubscription(Channel.kt:31)
backend_1         | 	at kotlinx.coroutines.reactive.ChannelKt.openSubscription$default(Channel.kt:30)
backend_1         | 	at org.litote.kmongo.coroutine.CoroutinePublisherKt.toList(CoroutinePublisher.kt:63)
backend_1         | 	at org.litote.kmongo.coroutine.CoroutinePublisher.toList(CoroutinePublisher.kt:48)
backend_1         | 	at personik.core.scheduledtasks.ScheduledTaskRepositoryMongo.getAndUpdateActiveTasks(ScheduledTaskRepository.kt:38)
...
```

The code that triggers the error looks like this:

```
return client.getDatabase(dbname).getCollection<ScheduledTask>("scheduledTasks").find(ScheduledTask::jobId eq jobId).toList()
```

**Comment by zigzago** [comment]
be sure do use the same coroutine lib version than KMongo https://github.com/Litote/kmongo/blob/master/pom.xml#L78

**Comment by alexanderfinn** [comment]
Actually, this only manifests with kotlinx.coroutines version 1.4, when I roll back to 1.3.8 everything works fine.

**Comment by zigzago** [comment]
next release of kmongo will use 1.4, for now you have to downgrade to 1.3.9 or lower

**Comment by sinhpn92** [comment]
Have any update anymore there? So I need to use kotlin 1.3.9?

**Comment by zigzago** [comment]
@sinhpn92  It should be ok with latest kmongo version - kmongo 4.2.3 uses coroutine 1.4.2
