### ISSUE TITLE
Kotlinx.Serialization: first level serialization is broken

### ISSUE THREAD

**Issue by dondish** [Litote/kmongo#248]
### How to reproduce:
1. Push a class with an instant to the Mongo collection
2. Find from the mongo collection
3. It should fail to deserialize

### Expected Behavior
It should deserialize to the correct class

### Actual Behavior
It fails to deserialize

### Additional case specific information:
Java 11, OpenJDK.
KMongo 4.2.1

Mongo Collection State:
```
db.schedulerJob.find()
{ "_id" : ObjectId("5fb7d2bfac8e4033d69c163f"), "startTime" : ISODate("2020-11-20T14:29:19.502Z"), "duration" : NumberLong(900000), "targetUserId" : "110433910835404800", "guildId" : "383210853270552578", "reason" : "Time's up!", "action" : "UNMUTE" }
```

Interface:
```kotlin
interface SchedulerJob {
    @Contextual @SerialName("_id") val id: Id<SchedulerJob>
    val action: Action
    @Contextual val startTime: Instant
    val duration: Long
    val targetUserId: String
    val guildId: String

    fun shouldBePersisted(): Boolean {
        return duration >= Duration.ofMinutes(15).toMillis()
    }

    suspend fun processJob()
}
```
Effective class:
```kotlin
@Serializable
class UnmuteSchedulerJob(
    @Contextual @SerialName("_id") override val id: Id<SchedulerJob> = newId(),
    @Contextual override val startTime: Instant = Instant.now(),
    override val duration: Long,
    override val targetUserId: String,
    override val guildId: String,
    val reason: String?
) : SchedulerJob {
    override val action: Action = Action.UNMUTE

    override suspend fun processJob() {
        val jda = KoinContextHandler.get().get<JDA>()
        val guild = jda.getGuildById(guildId) ?: return

        val moderationService = KoinContextHandler.get().get<IModerationService>()

        moderationService.unmute(targetUserId, guild, reason)
    }
}
```

Exception Log:
```
Exception in thread "pool-3-thread-1" org.bson.BsonInvalidOperationException: readString can only be called when CurrentBSONType is STRING, not when CurrentBSONType is DATE_TIME.
	at org.bson.AbstractBsonReader.verifyBSONType(AbstractBsonReader.java:690)
	at org.bson.AbstractBsonReader.checkPreconditions(AbstractBsonReader.java:722)
	at org.bson.AbstractBsonReader.readString(AbstractBsonReader.java:457)
	at com.github.jershell.kbson.FlexibleDecoder.decodeString(BsonFlexibleDecoder.kt:114)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeStringElement(AbstractDecoder.kt:56)
	at kotlinx.serialization.internal.AbstractPolymorphicSerializer.deserialize(AbstractPolymorphicSerializer.kt:52)
	at kotlinx.serialization.encoding.Decoder$DefaultImpls.decodeSerializableValue(Decoding.kt:234)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:17)
	at org.litote.kmongo.serialization.SerializationCodec.decode(SerializationCodec.kt:69)
	at com.mongodb.internal.operation.CommandResultArrayCodec.decode(CommandResultArrayCodec.java:52)
	at com.mongodb.internal.operation.CommandResultDocumentCodec.readValue(CommandResultDocumentCodec.java:60)
	at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:87)
	at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:42)
	at org.bson.internal.LazyCodec.decode(LazyCodec.java:48)
	at org.bson.codecs.BsonDocumentCodec.readValue(BsonDocumentCodec.java:104)
	at com.mongodb.internal.operation.CommandResultDocumentCodec.readValue(CommandResultDocumentCodec.java:63)
	at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:87)
	at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:42)
	at com.mongodb.internal.connection.ReplyMessage.<init>(ReplyMessage.java:51)
	at com.mongodb.internal.connection.InternalStreamConnection.getCommandResult(InternalStreamConnection.java:477)
	at com.mongodb.internal.connection.InternalStreamConnection.access$1000(InternalStreamConnection.java:78)
	at com.mongodb.internal.connection.InternalStreamConnection$2$1.onResult(InternalStreamConnection.java:462)
	at com.mongodb.internal.connection.InternalStreamConnection$2$1.onResult(InternalStreamConnection.java:440)
	at com.mongodb.internal.connection.InternalStreamConnection$MessageHeaderCallback$MessageCallback.onResult(InternalStreamConnection.java:745)
	at com.mongodb.internal.connection.InternalStreamConnection$MessageHeaderCallback$MessageCallback.onResult(InternalStreamConnection.java:712)
	at com.mongodb.internal.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:582)
	at com.mongodb.internal.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:579)
	at com.mongodb.internal.connection.AsynchronousChannelStream$BasicCompletionHandler.completed(AsynchronousChannelStream.java:250)
	at com.mongodb.internal.connection.AsynchronousChannelStream$BasicCompletionHandler.completed(AsynchronousChannelStream.java:233)
	at java.base/sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:127)
	at java.base/sun.nio.ch.Invoker.invokeDirect(Invoker.java:158)
	at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.implRead(UnixAsynchronousSocketChannelImpl.java:562)
	at java.base/sun.nio.ch.AsynchronousSocketChannelImpl.read(AsynchronousSocketChannelImpl.java:277)
	at java.base/sun.nio.ch.AsynchronousSocketChannelImpl.read(AsynchronousSocketChannelImpl.java:298)
	at com.mongodb.internal.connection.AsynchronousSocketChannelStream$AsynchronousSocketChannelAdapter.read(AsynchronousSocketChannelStream.java:144)
	at com.mongodb.internal.connection.AsynchronousChannelStream.readAsync(AsynchronousChannelStream.java:118)
	at com.mongodb.internal.connection.AsynchronousChannelStream.readAsync(AsynchronousChannelStream.java:107)
	at com.mongodb.internal.connection.InternalStreamConnection.readAsync(InternalStreamConnection.java:579)
	at com.mongodb.internal.connection.InternalStreamConnection.access$1100(InternalStreamConnection.java:78)
	at com.mongodb.internal.connection.InternalStreamConnection$MessageHeaderCallback.onResult(InternalStreamConnection.java:702)
	at com.mongodb.internal.connection.InternalStreamConnection$MessageHeaderCallback.onResult(InternalStreamConnection.java:687)
	at com.mongodb.internal.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:582)
	at com.mongodb.internal.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:579)
	at com.mongodb.internal.connection.AsynchronousChannelStream$BasicCompletionHandler.completed(AsynchronousChannelStream.java:250)
	at com.mongodb.internal.connection.AsynchronousChannelStream$BasicCompletionHandler.completed(AsynchronousChannelStream.java:233)
	at java.base/sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:127)
	at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.finishRead(UnixAsynchronousSocketChannelImpl.java:439)
	at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.finish(UnixAsynchronousSocketChannelImpl.java:191)
	at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.onEvent(UnixAsynchronousSocketChannelImpl.java:213)
	at java.base/sun.nio.ch.EPollPort$EventHandlerTask.run(EPollPort.java:306)
	at java.base/sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:112)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by zigzago** [comment]
Hello,

The issue is not with Instant but with polymorphism. You need to register the polymorphism module (look at kotlinx.serialization sample: https://github.com/Kotlin/kotlinx.serialization/blob/master/guide/example/example-poly-10.kt ) and register the module in KMongo using `registerModule` (see https://litote.org/kmongo/object-mapping/#additional-modules-and-serializers )

HTH

**Comment by dondish** [comment]
I registered a module and a serializer, both options didn't work
```kotlin
registerModule(SerializersModule {
            polymorphic(SchedulerJob::class) {
                subclass(BanSchedulerJob::class, BanSchedulerJob.serializer())
                subclass(KickSchedulerJob::class, KickSchedulerJob.serializer())
                subclass(MuteSchedulerJob::class, MuteSchedulerJob.serializer())
                subclass(UnbanSchedulerJob::class, UnbanSchedulerJob.serializer())
                subclass(UnmuteSchedulerJob::class, UnmuteSchedulerJob.serializer())
            }
        })
        registerSerializer(PolymorphicSerializer(SchedulerJob::class))
```
I also tried both options seperately, didn't work.

**Comment by dondish** [comment]
I also noticed it didn't put the type in the mongodb document

**Comment by zigzago** [comment]
Try to serialize and deserialize in json using only kotlinx.serialization (without KMongo) (see doc https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/basic-serialization.md#basics )

Does json serialization and deserialization is ok ?

**Comment by dondish** [comment]
I can't check because your serializer for Instant are exclusively BSON.

**Comment by zigzago** [comment]
remove the Instant property for your test ;)

**Comment by dondish** [comment]
I debugged and it seems like when I use Json it does add the type to the serialized object and on Bson it doesn't.

**Comment by zigzago** [comment]
There is a regression in the kotlinx.serialization KMongo codec: first level polymorphism serialization is broken (it works if the class is embedded in an other class). I'm going to release a 4.2.2 version.

**Comment by zigzago** [comment]
By the way I found an other annoying bug (see #249). Expect a new bug fix release in a few days (a fix on third-party library kbson is required)
