### ISSUE TITLE
update extensions

### ISSUE THREAD

**Issue by kittenfromvoid** [Litote/kmongo#257]
Hi I encountered weird thing and I am wondering if I am doing something wrong
version is current realease (org.litote.kmongo:kmongo-coroutine-serialization:4.2.3)

it happens with addToSet too
``` 
database.getCollection<User>()
        .updateOneById(
            user._id,
         User::tokens push Token(token, Token.Type.LOGIN) // <--- doesnt work
       // push(User::tokens,  Token(token, Token.Type.LOGIN)) <--- works fine
        )
```
exception:

```Serializer for class 'BsonField' is not found.
Mark the class as @Serializable or provide the serializer explicitly.
kotlinx.serialization.SerializationException: Serializer for class 'BsonField' is not found.
Mark the class as @Serializable or provide the serializer explicitly.
	at kotlinx.serialization.internal.Platform_commonKt.serializerNotRegistered(Platform.common.kt:91)
	at kotlinx.serialization.SerializersKt__SerializersKt.serializer(Serializers.kt:130)
	at kotlinx.serialization.SerializersKt.serializer(Unknown Source)
	at org.litote.kmongo.serialization.KMongoSerializationRepository.getSerializer(KMongoSerializationRepository.kt:180)
	at org.litote.kmongo.serialization.SerializationCodec.encode(SerializationCodec.kt:62)
	at org.litote.kmongo.serialization.SerializationClassMappingTypeService.filterIdToBson(SerializationClassMappingTypeService.kt:59)
	at org.litote.kmongo.service.ClassMappingType.filterIdToBson(ClassMappingType.kt)
	at org.litote.kmongo.util.KMongoUtil.filterIdToBson(KMongoUtil.kt:149)
	at org.litote.kmongo.util.KMongoUtil.setModifier(KMongoUtil.kt:182)
	at org.litote.kmongo.util.KMongoUtil.toBsonModifier(KMongoUtil.kt:175)
	at org.litote.kmongo.coroutine.CoroutineCollection.updateOneById(CoroutineCollection.kt:1462)
	at org.litote.kmongo.coroutine.CoroutineCollection.updateOneById$default(CoroutineCollection.kt:1458)
	at eu.xetoo.healthygoat.routes.AuthKt.login(Auth.kt:85)
	at eu.xetoo.healthygoat.routes.AuthKt$login$1.invokeSuspend(Auth.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Comment by zigzago** [comment]
Yes, this is WAD. The push extension on KProperty returns a BsonField that must be used only for group operations as documented ( https://litote.org/kmongo/dokka/kmongo/org.litote.kmongo/kotlin.reflect.-k-property/push.html ). But the push function ( https://litote.org/kmongo/dokka/kmongo/org.litote.kmongo/push.html ) works fine with update operations.

I agree that it is error prone, but it is inherited from java driver. I'm going to add a more meaningful error though. Wait for #214 to get a better solution.
