### ISSUE TITLE
SSL Handshake error with valid CA cert

### ISSUE THREAD

**Issue by unredundant** [Litote/kmongo#304]
Hello,

I am trying to connect mongo to a database protected by TLS.  I have setup the connection string as follows 

```
mongodb+srv://${USER}:${PASSWORD}@${HOST}/${DATABASE}?authSource=admin&tlsCAFile=${FILE_PATH}
```

I have confirmed that the connection can be established both via the mongo CLI as well as in the Intellij database explorer, so I'm fairly confident that this is an issue with my kmongo configuration (hopefully) or with Kmongo itself (hopefully not).  

My kmongo builder is relatively simple

```kotlin
val client = KMongo.createClient(MongoClientSettings.builder()
      .applyConnectionString(ConnectionString(connectionUri)
      .uuidRepresentation(UuidRepresentation.STANDARD)
      .build())
```

The resulting error is 

```
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:439)
	at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:306)
	at java.base/sun.security.validator.Validator.validate(Validator.java:264)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:231)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:132)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1341)
	... 24 common frames omitted
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
	at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
	at java.base/java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297)
	at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:434)
	... 29 common frames omitted
```

I am running on the latest release of Kmongo :) `4.3.0`

**Comment by zigzago** [comment]
Hello,

This is not a kmongo issue :). This page could help: https://mongodb.github.io/mongo-java-driver/3.4/driver/tutorials/ssl/#jvm-system-properties-for-tls-ssl

**Comment by rescribet** [comment]
Running into the same issue on DigitalOcean. The documentation there seems to state the certificates need to be set up via the file system. Is there no way to make this work via the environment?

**Comment by rescribet** [comment]
Made it work

https://gist.github.com/rescribet/8a710e957151b2aa1e464e32a127f0e9

**Comment by zigzago** [comment]
Thank you
