### ISSUE TITLE
kotlinx-serialization - "Maximum serialization depth exceeded" when inserting object with `Path` property

### ISSUE THREAD

**Issue by dosier** [Litote/kmongo#307]
Hi, for some reason I am getting a BsonSerializationException when inserting an object with a Path property. Maybe this is not related to kmongo at all, I am not sure. Does anyone have an idea on what might go wrong here?

Code:
```kt
@Serializable
data class Bla(@Serializable(with = PathSerializer::class) var path: Path)

object PathSerializer : KSerializer<Path> {
    override val descriptor = PrimitiveSerialDescriptor("Path", PrimitiveKind.STRING)
    override fun serialize(encoder: Encoder, value: Path) = encoder.encodeString(value.toAbsolutePath().toString())
    override fun deserialize(decoder: Decoder): Path = Path.of(decoder.decodeString())
}

@ExperimentalTime
internal class PathPropertyTest {

    @get:Rule
    val rule = KFlapdoodleRule(Bla::class)

    @Test
    fun `insert a bla`(){
        rule.col.insertOne(Bla(Paths.get("e"))) // throws
    }
}
```

Stacktrace:
```
Maximum serialization depth exceeded (does the object being serialized have a circular reference?).
org.bson.BsonSerializationException: Maximum serialization depth exceeded (does the object being serialized have a circular reference?).
	at org.bson.AbstractBsonWriter.writeStartArray(AbstractBsonWriter.java:331)
	at com.mongodb.internal.connection.BsonWriterDecorator.writeStartArray(BsonWriterDecorator.java:63)
	at com.mongodb.internal.connection.LevelCountingBsonWriter.writeStartArray(LevelCountingBsonWriter.java:54)
	at com.mongodb.internal.connection.IdHoldingBsonWriter.writeStartArray(IdHoldingBsonWriter.java:113)
	at org.bson.codecs.IterableCodec.encode(IterableCodec.java:102)
	at org.bson.codecs.IterableCodec.encode(IterableCodec.java:37)
	at org.bson.internal.LazyCodec.encode(LazyCodec.java:38)
	at org.bson.codecs.EncoderContext.encodeWithChildContext(EncoderContext.java:91)
	at org.bson.codecs.IterableCodec.writeValue(IterableCodec.java:120)
	at org.bson.codecs.IterableCodec.encode(IterableCodec.java:104)
	at org.bson.codecs.IterableCodec.encode(IterableCodec.java:37)
	at org.bson.internal.LazyCodec.encode(LazyCodec.java:38)
	at org.bson.codecs.EncoderContext.encodeWithChildContext(EncoderContext.java:91)
	at org.bson.codecs.IterableCodec.writeValue(IterableCodec.java:120)
	at org.bson.codecs.IterableCodec.encode(IterableCodec.java:104)
	at org.bson.codecs.IterableCodec.encode(IterableCodec.java:37)
	at org.bson.internal.LazyCodec.encode(LazyCodec.java:38)
       (repeats the last 5 lines in the stacktrace until max depth is exceeded)

```

**Comment by zigzago** [comment]
I do not reproduce the bug. Look at my unit test https://github.com/Litote/kmongo/commit/0ae151adda35e08001142410081194cd88fe6871

**Comment by dosier** [comment]
> I do not reproduce the bug. Look at my unit test [0ae151a](https://github.com/Litote/kmongo/commit/0ae151adda35e08001142410081194cd88fe6871)

Hmmm, very curious. When I run your test in this repository I also don't reproduce the bug. It seems to setup the test client differently. I get the following logs (before the exception) when I run my test in my own repository:
```
[Test worker] INFO de.flapdoodle.embed.mongo.MongodExecutable - start de.flapdoodle.embed.mongo.config.MongodConfigBuilder$ImmutableMongodConfig@6e628c6e
[Test worker] INFO org.mongodb.driver.cluster - Cluster created with settings {hosts=[127.0.0.1:56348], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms'}
[cluster-ClusterId{value='619a6664e0fe00353877a6ff', description='null'}-127.0.0.1:56348] INFO org.mongodb.driver.connection - Opened connection [connectionId{localValue:1, serverValue:1}] to 127.0.0.1:56348
[cluster-rtt-ClusterId{value='619a6664e0fe00353877a6ff', description='null'}-127.0.0.1:56348] INFO org.mongodb.driver.connection - Opened connection [connectionId{localValue:2, serverValue:2}] to 127.0.0.1:56348
[cluster-ClusterId{value='619a6664e0fe00353877a6ff', description='null'}-127.0.0.1:56348] INFO org.mongodb.driver.cluster - Monitor thread successfully connected to server with description ServerDescription{address=127.0.0.1:56348, type=STANDALONE, state=CONNECTED, ok=true, minWireVersion=0, maxWireVersion=7, maxDocumentSize=16777216, logicalSessionTimeoutMinutes=30, roundTripTimeNanos=21269791}
[Test worker] INFO org.mongodb.driver.connection - Opened connection [connectionId{localValue:3, serverValue:3}] to 127.0.0.1:56348
```
I am using the following deps:
```
    implementation("org.litote.kmongo:kmongo-native:$kmongoVersion")
    implementation("org.litote.kmongo:kmongo-flapdoodle:$kmongoVersion")
```

I get the following logs when I run the test you committed:

```
[main] INFO de.flapdoodle.embed.mongo.MongodExecutable - start de.flapdoodle.embed.mongo.config.MongodConfigBuilder$ImmutableMongodConfig@778d1062
[main] INFO de.flapdoodle.embed.mongo.MongodExecutable - start de.flapdoodle.embed.mongo.config.MongodConfigBuilder$ImmutableMongodConfig@1f3f4916
[main] INFO de.flapdoodle.embed.mongo.MongodExecutable - start de.flapdoodle.embed.mongo.config.MongodConfigBuilder$ImmutableMongodConfig@59d016c9
[main] INFO org.mongodb.driver.cluster - Cluster created with settings {hosts=[127.0.0.1:56141], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms'}
[main] INFO org.mongodb.driver.cluster - Cluster description not yet available. Waiting for 30000 ms before timing out
[cluster-ClusterId{value='619a65ecae91f94420b7e0fb', description='null'}-127.0.0.1:56141] INFO org.mongodb.driver.connection - Opened connection [connectionId{localValue:2, serverValue:2}] to 127.0.0.1:56141
[cluster-rtt-ClusterId{value='619a65ecae91f94420b7e0fb', description='null'}-127.0.0.1:56141] INFO org.mongodb.driver.connection - Opened connection [connectionId{localValue:1, serverValue:1}] to 127.0.0.1:56141
[cluster-ClusterId{value='619a65ecae91f94420b7e0fb', description='null'}-127.0.0.1:56141] INFO org.mongodb.driver.cluster - Monitor thread successfully connected to server with description ServerDescription{address=127.0.0.1:56141, type=REPLICA_SET_GHOST, state=CONNECTED, ok=true, minWireVersion=0, maxWireVersion=7, maxDocumentSize=16777216, logicalSessionTimeoutMinutes=30, roundTripTimeNanos=17119092, setName='null', canonicalAddress=null, hosts=[], passives=[], arbiters=[], primary='null', tagSet=TagSet{[]}, electionId=null, setVersion=null, topologyVersion=null, lastWriteDate=null, lastUpdateTimeNanos=257619042673709}
[main] INFO org.mongodb.driver.connection - Opened connection [connectionId{localValue:3, serverValue:3}] to 127.0.0.1:56141
[main] INFO org.mongodb.driver.cluster - Cluster created with settings {hosts=[127.0.0.1:56141], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms'}
[main] INFO org.mongodb.driver.cluster - Cluster description not yet available. Waiting for 30000 ms before timing out
[cluster-rtt-ClusterId{value='619a65f1ae91f94420b7e0fc', description='null'}-127.0.0.1:56141] INFO org.mongodb.driver.connection - Opened connection [connectionId{localValue:5, serverValue:11}] to 127.0.0.1:56141
[cluster-ClusterId{value='619a65f1ae91f94420b7e0fc', description='null'}-127.0.0.1:56141] INFO org.mongodb.driver.connection - Opened connection [connectionId{localValue:4, serverValue:10}] to 127.0.0.1:56141
[cluster-ClusterId{value='619a65f1ae91f94420b7e0fc', description='null'}-127.0.0.1:56141] INFO org.mongodb.driver.cluster - Monitor thread successfully connected to server with description ServerDescription{address=127.0.0.1:56141, type=REPLICA_SET_SECONDARY, state=CONNECTED, ok=true, minWireVersion=0, maxWireVersion=7, maxDocumentSize=16777216, logicalSessionTimeoutMinutes=30, roundTripTimeNanos=2588450, setName='kmongo', canonicalAddress=127.0.0.1:56141, hosts=[127.0.0.1:56141, 127.0.0.1:56142, 127.0.0.1:56143], passives=[], arbiters=[], primary='null', tagSet=TagSet{[]}, electionId=null, setVersion=1, topologyVersion=null, lastWriteDate=Sun Nov 21 16:29:51 CET 2021, lastUpdateTimeNanos=257623994994581}
[main] INFO org.mongodb.driver.connection - Opened connection [connectionId{localValue:6, serverValue:12}] to 127.0.0.1:56141
[main] INFO org.mongodb.driver.cluster - Cluster created with settings {hosts=[127.0.0.1:56141, 127.0.0.1:56142, 127.0.0.1:56143], mode=MULTIPLE, requiredClusterType=REPLICA_SET, serverSelectionTimeout='30000 ms', requiredReplicaSetName='kmongo'}
[main] INFO org.mongodb.driver.cluster - Adding discovered server 127.0.0.1:56141 to client view of cluster
[main] INFO org.mongodb.driver.cluster - Adding discovered server 127.0.0.1:56142 to client view of cluster
[main] INFO org.mongodb.driver.cluster - Adding discovered server 127.0.0.1:56143 to client view of cluster
[cluster-rtt-ClusterId{value='619a65f1ae91f94420b7e0fd', description='null'}-127.0.0.1:56141] INFO org.mongodb.driver.connection - Opened connection [connectionId{localValue:8, serverValue:16}] to 127.0.0.1:56141
[cluster-ClusterId{value='619a65f1ae91f94420b7e0fd', description='null'}-127.0.0.1:56141] INFO org.mongodb.driver.connection - Opened connection [connectionId{localValue:7, serverValue:15}] to 127.0.0.1:56141
[cluster-ClusterId{value='619a65f1ae91f94420b7e0fd', description='null'}-127.0.0.1:56141] INFO org.mongodb.driver.cluster - Monitor thread successfully connected to server with description ServerDescription{address=127.0.0.1:56141, type=REPLICA_SET_SECONDARY, state=CONNECTED, ok=true, minWireVersion=0, maxWireVersion=7, maxDocumentSize=16777216, logicalSessionTimeoutMinutes=30, roundTripTimeNanos=1425704, setName='kmongo', canonicalAddress=127.0.0.1:56141, hosts=[127.0.0.1:56141, 127.0.0.1:56142, 127.0.0.1:56143], passives=[], arbiters=[], primary='null', tagSet=TagSet{[]}, electionId=null, setVersion=62705, topologyVersion=null, lastWriteDate=Sun Nov 21 16:29:51 CET 2021, lastUpdateTimeNanos=257624035730477}
[cluster-ClusterId{value='619a65f1ae91f94420b7e0fd', description='null'}-127.0.0.1:56142] INFO org.mongodb.driver.connection - Opened connection [connectionId{localValue:9, serverValue:5}] to 127.0.0.1:56142
[cluster-rtt-ClusterId{value='619a65f1ae91f94420b7e0fd', description='null'}-127.0.0.1:56142] INFO org.mongodb.driver.connection - Opened connection [connectionId{localValue:10, serverValue:6}] to 127.0.0.1:56142
[cluster-ClusterId{value='619a65f1ae91f94420b7e0fd', description='null'}-127.0.0.1:56142] INFO org.mongodb.driver.cluster - Monitor thread successfully connected to server with description ServerDescription{address=127.0.0.1:56142, type=REPLICA_SET_GHOST, state=CONNECTED, ok=true, minWireVersion=0, maxWireVersion=7, maxDocumentSize=16777216, logicalSessionTimeoutMinutes=30, roundTripTimeNanos=1297599, setName='null', canonicalAddress=null, hosts=[], passives=[], arbiters=[], primary='null', tagSet=TagSet{[]}, electionId=null, setVersion=null, topologyVersion=null, lastWriteDate=null, lastUpdateTimeNanos=257624036665807}
[cluster-ClusterId{value='619a65f1ae91f94420b7e0fd', description='null'}-127.0.0.1:56142] INFO org.mongodb.driver.cluster - Server 127.0.0.1:56142 does not appear to be a member of an initiated replica set.
[cluster-ClusterId{value='619a65f1ae91f94420b7e0fd', description='null'}-127.0.0.1:56143] INFO org.mongodb.driver.connection - Opened connection [connectionId{localValue:11, serverValue:5}] to 127.0.0.1:56143
[cluster-rtt-ClusterId{value='619a65f1ae91f94420b7e0fd', description='null'}-127.0.0.1:56143] INFO org.mongodb.driver.connection - Opened connection [connectionId{localValue:12, serverValue:6}] to 127.0.0.1:56143
[cluster-ClusterId{value='619a65f1ae91f94420b7e0fd', description='null'}-127.0.0.1:56143] INFO org.mongodb.driver.cluster - Monitor thread successfully connected to server with description ServerDescription{address=127.0.0.1:56143, type=REPLICA_SET_GHOST, state=CONNECTED, ok=true, minWireVersion=0, maxWireVersion=7, maxDocumentSize=16777216, logicalSessionTimeoutMinutes=30, roundTripTimeNanos=1168836, setName='null', canonicalAddress=null, hosts=[], passives=[], arbiters=[], primary='null', tagSet=TagSet{[]}, electionId=null, setVersion=null, topologyVersion=null, lastWriteDate=null, lastUpdateTimeNanos=257624037682464}
[cluster-ClusterId{value='619a65f1ae91f94420b7e0fd', description='null'}-127.0.0.1:56143] INFO org.mongodb.driver.cluster - Server 127.0.0.1:56143 does not appear to be a member of an initiated replica set.
[main] INFO org.mongodb.driver.cluster - No server chosen by WritableServerSelector from cluster description ClusterDescription{type=REPLICA_SET, connectionMode=MULTIPLE, serverDescriptions=[ServerDescription{address=127.0.0.1:56143, type=REPLICA_SET_GHOST, state=CONNECTED, ok=true, minWireVersion=0, maxWireVersion=7, maxDocumentSize=16777216, logicalSessionTimeoutMinutes=30, roundTripTimeNanos=1168836, setName='null', canonicalAddress=null, hosts=[], passives=[], arbiters=[], primary='null', tagSet=TagSet{[]}, electionId=null, setVersion=null, topologyVersion=null, lastWriteDate=null, lastUpdateTimeNanos=257624037682464}, ServerDescription{address=127.0.0.1:56142, type=REPLICA_SET_GHOST, state=CONNECTED, ok=true, minWireVersion=0, maxWireVersion=7, maxDocumentSize=16777216, logicalSessionTimeoutMinutes=30, roundTripTimeNanos=1297599, setName='null', canonicalAddress=null, hosts=[], passives=[], arbiters=[], primary='null', tagSet=TagSet{[]}, electionId=null, setVersion=null, topologyVersion=null, lastWriteDate=null, lastUpdateTimeNanos=257624036665807}, ServerDescription{address=127.0.0.1:56141, type=REPLICA_SET_SECONDARY, state=CONNECTED, ok=true, minWireVersion=0, maxWireVersion=7, maxDocumentSize=16777216, logicalSessionTimeoutMinutes=30, roundTripTimeNanos=1425704, setName='kmongo', canonicalAddress=127.0.0.1:56141, hosts=[127.0.0.1:56141, 127.0.0.1:56142, 127.0.0.1:56143], passives=[], arbiters=[], primary='null', tagSet=TagSet{[]}, electionId=null, setVersion=62705, topologyVersion=null, lastWriteDate=Sun Nov 21 16:29:51 CET 2021, lastUpdateTimeNanos=257624035730477}]}. Waiting for 30000 ms before timing out
[cluster-ClusterId{value='619a65f1ae91f94420b7e0fd', description='null'}-127.0.0.1:56143] INFO org.mongodb.driver.cluster - Server 127.0.0.1:56143 does not appear to be a member of an initiated replica set.
[cluster-ClusterId{value='619a65f1ae91f94420b7e0fd', description='null'}-127.0.0.1:56142] INFO org.mongodb.driver.cluster - Server 127.0.0.1:56142 does not appear to be a member of an initiated replica set.
[cluster-ClusterId{value='619a65f1ae91f94420b7e0fd', description='null'}-127.0.0.1:56143] INFO org.mongodb.driver.cluster - Server 127.0.0.1:56143 does not appear to be a member of an initiated replica set.
[cluster-ClusterId{value='619a65f1ae91f94420b7e0fd', description='null'}-127.0.0.1:56142] INFO org.mongodb.driver.cluster - Server 127.0.0.1:56142 does not appear to be a member of an initiated replica set.
[cluster-ClusterId{value='619a65f1ae91f94420b7e0fd', description='null'}-127.0.0.1:56142] INFO org.mongodb.driver.cluster - Server 127.0.0.1:56142 does not appear to be a member of an initiated replica set.
[cluster-ClusterId{value='619a65f1ae91f94420b7e0fd', description='null'}-127.0.0.1:56143] INFO org.mongodb.driver.cluster - Server 127.0.0.1:56143 does not appear to be a member of an initiated replica set.
[cluster-ClusterId{value='619a65f1ae91f94420b7e0fd', description='null'}-127.0.0.1:56143] INFO org.mongodb.driver.cluster - Server 127.0.0.1:56143 does not appear to be a member of an initiated replica set.
[cluster-ClusterId{value='619a65f1ae91f94420b7e0fd', description='null'}-127.0.0.1:56142] INFO org.mongodb.driver.cluster - Monitor thread successfully connected to server with description ServerDescription{address=127.0.0.1:56142, type=REPLICA_SET_OTHER, state=CONNECTED, ok=true, minWireVersion=0, maxWireVersion=7, maxDocumentSize=16777216, logicalSessionTimeoutMinutes=30, roundTripTimeNanos=1284508, setName='kmongo', canonicalAddress=127.0.0.1:56142, hosts=[127.0.0.1:56141, 127.0.0.1:56142, 127.0.0.1:56143], passives=[], arbiters=[], primary='null', tagSet=TagSet{[]}, electionId=null, setVersion=62705, topologyVersion=null, lastWriteDate=Thu Jan 01 01:00:00 CET 1970, lastUpdateTimeNanos=257626052161000}
[cluster-ClusterId{value='619a65f1ae91f94420b7e0fd', description='null'}-127.0.0.1:56143] INFO org.mongodb.driver.cluster - Monitor thread successfully connected to server with description ServerDescription{address=127.0.0.1:56143, type=REPLICA_SET_OTHER, state=CONNECTED, ok=true, minWireVersion=0, maxWireVersion=7, maxDocumentSize=16777216, logicalSessionTimeoutMinutes=30, roundTripTimeNanos=1165250, setName='kmongo', canonicalAddress=127.0.0.1:56143, hosts=[127.0.0.1:56141, 127.0.0.1:56142, 127.0.0.1:56143], passives=[], arbiters=[], primary='null', tagSet=TagSet{[]}, electionId=null, setVersion=62705, topologyVersion=null, lastWriteDate=Thu Jan 01 01:00:00 CET 1970, lastUpdateTimeNanos=257626556775837}
[cluster-ClusterId{value='619a65ecae91f94420b7e0fb', description='null'}-127.0.0.1:56141] INFO org.mongodb.driver.cluster - Monitor thread successfully connected to server with description ServerDescription{address=127.0.0.1:56141, type=REPLICA_SET_SECONDARY, state=CONNECTED, ok=true, minWireVersion=0, maxWireVersion=7, maxDocumentSize=16777216, logicalSessionTimeoutMinutes=30, roundTripTimeNanos=17105813, setName='kmongo', canonicalAddress=127.0.0.1:56141, hosts=[127.0.0.1:56141, 127.0.0.1:56142, 127.0.0.1:56143], passives=[], arbiters=[], primary='null', tagSet=TagSet{[]}, electionId=null, setVersion=62705, topologyVersion=null, lastWriteDate=Sun Nov 21 16:29:51 CET 2021, lastUpdateTimeNanos=257629048827098}
[cluster-ClusterId{value='619a65f1ae91f94420b7e0fd', description='null'}-127.0.0.1:56143] INFO org.mongodb.driver.cluster - Monitor thread successfully connected to server with description ServerDescription{address=127.0.0.1:56143, type=REPLICA_SET_SECONDARY, state=CONNECTED, ok=true, minWireVersion=0, maxWireVersion=7, maxDocumentSize=16777216, logicalSessionTimeoutMinutes=30, roundTripTimeNanos=1165250, setName='kmongo', canonicalAddress=127.0.0.1:56143, hosts=[127.0.0.1:56141, 127.0.0.1:56142, 127.0.0.1:56143], passives=[], arbiters=[], primary='null', tagSet=TagSet{[]}, electionId=null, setVersion=62705, topologyVersion=null, lastWriteDate=Sun Nov 21 16:29:51 CET 2021, lastUpdateTimeNanos=257632595364728}
[cluster-ClusterId{value='619a65f1ae91f94420b7e0fd', description='null'}-127.0.0.1:56142] INFO org.mongodb.driver.cluster - Monitor thread successfully connected to server with description ServerDescription{address=127.0.0.1:56142, type=REPLICA_SET_SECONDARY, state=CONNECTED, ok=true, minWireVersion=0, maxWireVersion=7, maxDocumentSize=16777216, logicalSessionTimeoutMinutes=30, roundTripTimeNanos=1284508, setName='kmongo', canonicalAddress=127.0.0.1:56142, hosts=[127.0.0.1:56141, 127.0.0.1:56142, 127.0.0.1:56143], passives=[], arbiters=[], primary='null', tagSet=TagSet{[]}, electionId=null, setVersion=62705, topologyVersion=null, lastWriteDate=Sun Nov 21 16:29:51 CET 2021, lastUpdateTimeNanos=257633099488575}
[cluster-ClusterId{value='619a65f1ae91f94420b7e0fc', description='null'}-127.0.0.1:56141] INFO org.mongodb.driver.cluster - Monitor thread successfully connected to server with description ServerDescription{address=127.0.0.1:56141, type=REPLICA_SET_SECONDARY, state=CONNECTED, ok=true, minWireVersion=0, maxWireVersion=7, maxDocumentSize=16777216, logicalSessionTimeoutMinutes=30, roundTripTimeNanos=2508966, setName='kmongo', canonicalAddress=127.0.0.1:56141, hosts=[127.0.0.1:56141, 127.0.0.1:56142, 127.0.0.1:56143], passives=[], arbiters=[], primary='null', tagSet=TagSet{[]}, electionId=null, setVersion=62705, topologyVersion=null, lastWriteDate=Sun Nov 21 16:29:51 CET 2021, lastUpdateTimeNanos=257634001044269}
[cluster-ClusterId{value='619a65f1ae91f94420b7e0fd', description='null'}-127.0.0.1:56141] INFO org.mongodb.driver.cluster - Monitor thread successfully connected to server with description ServerDescription{address=127.0.0.1:56141, type=REPLICA_SET_SECONDARY, state=CONNECTED, ok=true, minWireVersion=0, maxWireVersion=7, maxDocumentSize=16777216, logicalSessionTimeoutMinutes=30, roundTripTimeNanos=1146332, setName='kmongo', canonicalAddress=127.0.0.1:56141, hosts=[127.0.0.1:56141, 127.0.0.1:56142, 127.0.0.1:56143], passives=[], arbiters=[], primary='127.0.0.1:56141', tagSet=TagSet{[]}, electionId=7fffffff0000000000000001, setVersion=62705, topologyVersion=null, lastWriteDate=Sun Nov 21 16:29:51 CET 2021, lastUpdateTimeNanos=257634610044243}
[cluster-ClusterId{value='619a65f1ae91f94420b7e0fd', description='null'}-127.0.0.1:56142] INFO org.mongodb.driver.cluster - Monitor thread successfully connected to server with description ServerDescription{address=127.0.0.1:56142, type=REPLICA_SET_SECONDARY, state=CONNECTED, ok=true, minWireVersion=0, maxWireVersion=7, maxDocumentSize=16777216, logicalSessionTimeoutMinutes=30, roundTripTimeNanos=1182578, setName='kmongo', canonicalAddress=127.0.0.1:56142, hosts=[127.0.0.1:56141, 127.0.0.1:56142, 127.0.0.1:56143], passives=[], arbiters=[], primary='127.0.0.1:56141', tagSet=TagSet{[]}, electionId=null, setVersion=62705, topologyVersion=null, lastWriteDate=Sun Nov 21 16:29:51 CET 2021, lastUpdateTimeNanos=257635114565882}
[cluster-ClusterId{value='619a65f1ae91f94420b7e0fd', description='null'}-127.0.0.1:56143] INFO org.mongodb.driver.cluster - Monitor thread successfully connected to server with description ServerDescription{address=127.0.0.1:56143, type=REPLICA_SET_SECONDARY, state=CONNECTED, ok=true, minWireVersion=0, maxWireVersion=7, maxDocumentSize=16777216, logicalSessionTimeoutMinutes=30, roundTripTimeNanos=1088779, setName='kmongo', canonicalAddress=127.0.0.1:56143, hosts=[127.0.0.1:56141, 127.0.0.1:56142, 127.0.0.1:56143], passives=[], arbiters=[], primary='127.0.0.1:56141', tagSet=TagSet{[]}, electionId=null, setVersion=62705, topologyVersion=null, lastWriteDate=Sun Nov 21 16:29:51 CET 2021, lastUpdateTimeNanos=257635114564367}
[cluster-ClusterId{value='619a65f1ae91f94420b7e0fd', description='null'}-127.0.0.1:56141] INFO org.mongodb.driver.cluster - Monitor thread successfully connected to server with description ServerDescription{address=127.0.0.1:56141, type=REPLICA_SET_PRIMARY, state=CONNECTED, ok=true, minWireVersion=0, maxWireVersion=7, maxDocumentSize=16777216, logicalSessionTimeoutMinutes=30, roundTripTimeNanos=1146332, setName='kmongo', canonicalAddress=127.0.0.1:56141, hosts=[127.0.0.1:56141, 127.0.0.1:56142, 127.0.0.1:56143], passives=[], arbiters=[], primary='127.0.0.1:56141', tagSet=TagSet{[]}, electionId=7fffffff0000000000000001, setVersion=62705, topologyVersion=null, lastWriteDate=Sun Nov 21 16:30:05 CET 2021, lastUpdateTimeNanos=257636120596784}
[cluster-ClusterId{value='619a65f1ae91f94420b7e0fd', description='null'}-127.0.0.1:56141] INFO org.mongodb.driver.cluster - Setting max election id to 7fffffff0000000000000001 from replica set primary 127.0.0.1:56141
[cluster-ClusterId{value='619a65f1ae91f94420b7e0fd', description='null'}-127.0.0.1:56141] INFO org.mongodb.driver.cluster - Setting max set version to 62705 from replica set primary 127.0.0.1:56141
[cluster-ClusterId{value='619a65f1ae91f94420b7e0fd', description='null'}-127.0.0.1:56141] INFO org.mongodb.driver.cluster - Discovered replica set primary 127.0.0.1:56141
[main] INFO org.mongodb.driver.connection - Opened connection [connectionId{localValue:13, serverValue:24}] to 127.0.0.1:56141
[cluster-ClusterId{value='619a65f1ae91f94420b7e0fd', description='null'}-127.0.0.1:56143] INFO org.mongodb.driver.cluster - Monitor thread successfully connected to server with description ServerDescription{address=127.0.0.1:56143, type=REPLICA_SET_OTHER, state=CONNECTED, ok=true, minWireVersion=0, maxWireVersion=7, maxDocumentSize=16777216, logicalSessionTimeoutMinutes=30, roundTripTimeNanos=1088779, setName='kmongo', canonicalAddress=127.0.0.1:56143, hosts=[127.0.0.1:56141, 127.0.0.1:56142, 127.0.0.1:56143], passives=[], arbiters=[], primary='127.0.0.1:56141', tagSet=TagSet{[]}, electionId=null, setVersion=62705, topologyVersion=null, lastWriteDate=Sun Nov 21 16:29:51 CET 2021, lastUpdateTimeNanos=257636620805041}
[cluster-ClusterId{value='619a65f1ae91f94420b7e0fd', description='null'}-127.0.0.1:56142] INFO org.mongodb.driver.cluster - Monitor thread successfully connected to server with description ServerDescription{address=127.0.0.1:56142, type=REPLICA_SET_OTHER, state=CONNECTED, ok=true, minWireVersion=0, maxWireVersion=7, maxDocumentSize=16777216, logicalSessionTimeoutMinutes=30, roundTripTimeNanos=1182578, setName='kmongo', canonicalAddress=127.0.0.1:56142, hosts=[127.0.0.1:56141, 127.0.0.1:56142, 127.0.0.1:56143], passives=[], arbiters=[], primary='127.0.0.1:56141', tagSet=TagSet{[]}, electionId=null, setVersion=62705, topologyVersion=null, lastWriteDate=Sun Nov 21 16:29:51 CET 2021, lastUpdateTimeNanos=257636622292530}
[Thread-0] INFO de.flapdoodle.embed.process.runtime.ProcessControl - stopOrDestroyProcess: process hasn't exited 
[cluster-ClusterId{value='619a65ecae91f94420b7e0fb', description='null'}-127.0.0.1:56141] INFO org.mongodb.driver.cluster - Monitor thread successfully connected to server with description ServerDescription{address=127.0.0.1:56141, type=REPLICA_SET_SECONDARY, state=CONNECTED, ok=true, minWireVersion=0, maxWireVersion=7, maxDocumentSize=16777216, logicalSessionTimeoutMinutes=30, roundTripTimeNanos=13899760, setName='kmongo', canonicalAddress=127.0.0.1:56141, hosts=[127.0.0.1:56141, 127.0.0.1:56142, 127.0.0.1:56143], passives=[], arbiters=[], primary='127.0.0.1:56141', tagSet=TagSet{[]}, electionId=7fffffff0000000000000001, setVersion=62705, topologyVersion=null, lastWriteDate=Sun Nov 21 16:30:06 CET 2021, lastUpdateTimeNanos=257639051288822}
[cluster-ClusterId{value='619a65f1ae91f94420b7e0fc', description='null'}-127.0.0.1:56141] INFO org.mongodb.driver.cluster - Monitor thread successfully connected to server with description ServerDescription{address=127.0.0.1:56141, type=REPLICA_SET_SECONDARY, state=CONNECTED, ok=true, minWireVersion=0, maxWireVersion=7, maxDocumentSize=16777216, logicalSessionTimeoutMinutes=30, roundTripTimeNanos=1904432, setName='kmongo', canonicalAddress=127.0.0.1:56141, hosts=[127.0.0.1:56141, 127.0.0.1:56142, 127.0.0.1:56143], passives=[], arbiters=[], primary='127.0.0.1:56141', tagSet=TagSet{[]}, electionId=7fffffff0000000000000001, setVersion=62705, topologyVersion=null, lastWriteDate=Sun Nov 21 16:30:06 CET 2021, lastUpdateTimeNanos=257644002041388}
[cluster-ClusterId{value='619a65f1ae91f94420b7e0fd', description='null'}-127.0.0.1:56141] INFO org.mongodb.driver.cluster - Monitor thread successfully connected to server with description ServerDescription{address=127.0.0.1:56141, type=REPLICA_SET_SECONDARY, state=CONNECTED, ok=true, minWireVersion=0, maxWireVersion=7, maxDocumentSize=16777216, logicalSessionTimeoutMinutes=30, roundTripTimeNanos=1039061, setName='kmongo', canonicalAddress=127.0.0.1:56141, hosts=[127.0.0.1:56141, 127.0.0.1:56142, 127.0.0.1:56143], passives=[], arbiters=[], primary='127.0.0.1:56141', tagSet=TagSet{[]}, electionId=7fffffff0000000000000001, setVersion=62705, topologyVersion=null, lastWriteDate=Sun Nov 21 16:30:06 CET 2021, lastUpdateTimeNanos=257646123611989}
Exception in thread "Thread-0" java.lang.IllegalStateException: Couldn't kill mongod process!

----------------------------------------------------
Something bad happend. We couldn't kill mongod process, and tried a lot.
If you want this problem solved you can help us if you open a new issue.

Follow this link:
https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/issues

Thank you:)
----------------------------------------------------


	at de.flapdoodle.embed.process.runtime.ProcessControl.waitForProcessGotKilled(ProcessControl.java:200)
	at de.flapdoodle.embed.process.runtime.ProcessControl.stop(ProcessControl.java:76)
	at de.flapdoodle.embed.process.runtime.AbstractProcess.stopProcess(AbstractProcess.java:196)
	at de.flapdoodle.embed.mongo.AbstractMongoProcess.stopInternal(AbstractMongoProcess.java:117)
	at de.flapdoodle.embed.process.runtime.AbstractProcess.stop(AbstractProcess.java:177)
	at de.flapdoodle.embed.process.runtime.Executable.stop(Executable.java:80)
	at de.flapdoodle.embed.process.runtime.Executable$JobKiller.run(Executable.java:97)
	at java.base/java.lang.Thread.run(Thread.java:831)
```

**Comment by zigzago** [comment]
you have to use kmongo-serialization and not kmongo-native as dependency ;)

**Comment by dosier** [comment]
> you have to use kmongo-serialization and not kmongo-native as dependency ;) https://litote.org/kmongo/quick-start/#object-mapping-engine

Ah shiit. Sorry for wasting your time.
