### ISSUE TITLE
Unable to create a client: IllegalAccessError

### ISSUE THREAD

**Issue by beau-ronin** [Litote/kmongo#322]
```
java.lang.IllegalAccessError: class org.litote.kmongo.KMongo tried to access method 'void org.bson.internal.OverridableUuidRepresentationCodecRegistry.<init>(org.bson.codecs.configuration.CodecProvider, org.bson.UuidRepresentation)' (org.litote.kmongo.KMongo and org.bson.internal.OverridableUuidRepresentationCodecRegistry are in unnamed module of loader 'app')
        at org.litote.kmongo.KMongo.createRegistry(KMongo.kt:82) ~[kmongo-core-4.5.0.jar:na]
        at org.litote.kmongo.KMongo.createClient(KMongo.kt:73) ~[kmongo-core-4.5.0.jar:na]
        at org.litote.kmongo.KMongo.createClient(KMongo.kt:59) ~[kmongo-core-4.5.0.jar:na]
        at org.litote.kmongo.KMongo.createClient(KMongo.kt:49) ~[kmongo-core-4.5.0.jar:na]
        at org.litote.kmongo.KMongo.createClient(KMongo.kt:41) ~[kmongo-core-4.5.0.jar:na]
```

**Comment by Legion2** [comment]
Same error here after updating to 4.5.0

**Comment by zigzago** [comment]
Hello,

Thank you for reporting.
What is the version of your jvm?

**Comment by zigzago** [comment]
Looks like you have a version on mongo java driver < 4.5.0 in your classpath. Check your dependency tree.

**Comment by beau-ronin** [comment]
Switched to 4.3 for now

**Comment by Legion2** [comment]
Also switch to 4.3. I use quarkus which enforced the mongodb client version to 4.3.3 and I was not able to override this version to 4.5.
