### ISSUE TITLE
Cannot deserialize a json object with error Cannot construct instance of `org.bson.json.JsonObject`

### ISSUE THREAD

**Issue by omkar-tenkale** [Litote/kmongo#387]
I've this database item model

```
data class PersonInDB(
    @JsonProperty("_id") var _id: String? = null,
    @JsonProperty("value")var value: org.bson.json.JsonObject,
)
```

but when trying to insert a document to db, i'm getting this error

```
com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `org.bson.json.JsonObject` (although at least one Creator exists): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [Source: de.undercouch.bson4jackson.io.LittleEndianInputStream@5f2a4d66; pos: 74] (through reference chain: com.myapp.db.PersonInDB["value"])
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:63)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1733)
	at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1358)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1420)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:352)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:185)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:542)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:564)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:439)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1405)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:352)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:185)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4730)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3738)
        ...
```

I tried making the value field type Gson's JsonObject and even kotlinx's JsonObject but similar errors are reported
How can I have a raw object field in my db model?  
<img width="219" alt="image" src="https://user-images.githubusercontent.com/39808155/204597312-b8e37c4d-5762-42d3-bdd3-8f9bae9336ae.png">

**Comment by omkar-tenkale** [comment]
Here's how I did it

```
import org.bson.Document
class JsonTestInDB (
    val data: Document
)

...

jsonInsertTestCollection.insertOne(
        JsonTestInDB( com.google.gson.JsonObject().apply {
            addProperty("price",23)
        }.asDocument())
)

...

val embeddedDocAsJsonObject: com.google.gson.JsonObject? =  jsonInsertTestCollection.findOne()?.data?.asJsonObject()

```

And here are the extension functions

```

fun JsonObject.asDocument() = Document(Gson().fromJson(toString(), object : TypeToken<Map<String, Any>>() {}.type))

fun Document.asJsonObject() = com.google.gson.JsonParser.parseString(toJson()) as JsonObject

inline fun <reified T> Document.parseAs(): T = Gson().fromJson(toJson(),T::class.java)

```

Hope this helps someone!
