### ISSUE TITLE
Fails to access the last field in a data class

### ISSUE THREAD

**Issue by Tea-Ayataka** [Litote/kmongo#70]
with the following exception:
```
Exception in thread "main" java.lang.IllegalStateException: it.accessor must not be null
	at org.litote.kmongo.jackson.JacksonClassMappingTypeService.getPath(JacksonClassMappingTypeService.kt:216)
	at org.litote.kmongo.service.ClassMappingType.getPath(ClassMappingType.kt)
	at org.litote.kmongo.PropertiesKt.path(Properties.kt:34)
	at org.litote.kmongo.FiltersKt.eq(Filters.kt:37)
```

Code:
`findOne(Account::isPatreon eq true)`

Data class:
```
data class Account(
        var email: String,
        var subscriptionEnds: Long,
        val servers: MutableList<Long> = mutableListOf(),
        var isPatreon: Boolean
)
```

**Comment by zigzago** [comment]
Thanks for reporting. The error comes from the "isX": Boolean syntax. 

Workaround: rename var isPatreon: Boolean into var patreon:Boolean

Fixed now in 3.8.1-SNAPSHOT and in 3.8.1 next week
