### ISSUE TITLE
Java 7 Compatibility 

### ISSUE THREAD

**Issue by andreasterrius** [Litote/kmongo#83]
Does kmongo supports java 1.7, if at all ?
It's unlikely that I can upgrade my instance's java version

Here's an example of the error 
```
Caused by: java.lang.UnsupportedClassVersionError: org/litote/kmongo/service/ClassMappingType : Unsupported major.minor version 52.0
at java.lang.ClassLoader.defineClass1(Native Method)
at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
at java.net.URLClassLoader.defineClass(URLClassLoader.java:442)
at java.net.URLClassLoader.access$100(URLClassLoader.java:64)
at java.net.URLClassLoader$1.run(URLClassLoader.java:354)
at java.net.URLClassLoader$1.run(URLClassLoader.java:348)
at java.security.AccessController.doPrivileged(Native Method)
at java.net.URLClassLoader.findClass(URLClassLoader.java:347)
at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:312)
at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
...
```

**Comment by zigzago** [comment]
KMongo is currently targeting java 8 class file format. But I've just pushed a version with java6 compatibility and the tests are ok. Please check kmongo 3.8.4-SNAPSHOT (using https://oss.sonatype.org/content/repositories/snapshots snapshots repo) and let me know if it is ok on your side.

**Comment by andreasterrius** [comment]
I tried the snapshot and found this error during runtime (registering the codec). Probably because java.time.Instant is only available on java 8
```
Caused by: java.lang.NoClassDefFoundError: java/time/Instant
	at org.litote.kmongo.jackson.ExtendedJsonModule.<init>(ExtendedJsonModule.kt:193)
	at org.litote.kmongo.jackson.ObjectMapperFactory.createExtendedJsonObjectMapper(ObjectMapperFactory.kt:31)
	at org.litote.kmongo.util.KMongoConfiguration.<clinit>(KMongoConfiguration.kt:35)
	at org.litote.kmongo.jackson.JacksonClassMappingTypeService.coreCodecRegistry(JacksonClassMappingTypeService.kt:192)
	at org.litote.kmongo.service.ClassMappingTypeService$DefaultImpls.codecRegistry(ClassMappingTypeService.kt:66)
	at org.litote.kmongo.jackson.JacksonClassMappingTypeService.codecRegistry(JacksonClassMappingTypeService.kt:142)
	at org.litote.kmongo.service.ClassMappingType.codecRegistry(ClassMappingType.kt)
	... 9 more
Caused by: java.lang.ClassNotFoundException: java.time.Instant
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	... 17 more
```

**Comment by zigzago** [comment]
@andreasterrius 
Digging further, it seems that [jackson-module-kotlin](https://github.com/FasterXML/jackson-module-kotlin), that KMongo uses under the hood, is itself not compatible with jdk7:
```
java.lang.NoSuchMethodError: java.lang.reflect.Method.getAnnotationsByType(Ljava/lang/Class;)[Ljava/lang/annotation/Annotation;

	at com.fasterxml.jackson.module.kotlin.KotlinAnnotationIntrospector.isRequiredByAnnotation(KotlinAnnotationIntrospector.kt:61)
```
But the Instant CNFE is now fixed for kmongo-native in the snapshot:
```
<dependency>
            <groupId>org.litote.kmongo</groupId>
            <artifactId>kmongo-native</artifactId>
            <version>3.8.4-SNAPSHOT</version>
</dependency>
```
 
I've been able to insert and find with kmongo-native & jdk7. Try it and let me know. But as mentioned by @jyemin (thanks!) soon you will need to upgrade anyway ;)

**Comment by zigzago** [comment]
will not do more than enable kmongo-native for jdk7
