### ISSUE TITLE
Can't connect

### ISSUE THREAD

**Issue by Miclebrick** [Litote/kmongo#98]
```
Caused by: java.lang.IllegalStateException: Service ClassMappingTypeService not found                                           
        at org.litote.kmongo.service.ClassMappingTypeKt$defaultService$2.invoke(ClassMappingType.kt:38) ~[?:?]                  
        at org.litote.kmongo.service.ClassMappingTypeKt$defaultService$2.invoke(ClassMappingType.kt) ~[?:?]                     
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74) ~[?:?]                                                           
        at org.litote.kmongo.service.ClassMappingTypeKt.getDefaultService(ClassMappingType.kt) ~[?:?]                          
        at org.litote.kmongo.service.ClassMappingTypeKt.getCurrentService(ClassMappingType.kt:49) ~[?:?]                       
        at org.litote.kmongo.service.ClassMappingTypeKt.access$getCurrentService$p(ClassMappingType.kt:1) ~[?:?]            
        at org.litote.kmongo.service.ClassMappingType.<init>(ClassMappingType.kt:57) ~[?:?]                                      
        at org.litote.kmongo.service.ClassMappingType.<clinit>(ClassMappingType.kt:57) ~[?:?]                               
        ... 15 more      
```

This error appears when trying to connect to the mongodb database.

**Comment by zigzago** [comment]
I do not reproduce. Whats is your configuration?

**Comment by Miclebrick** [comment]
I think it's not loading the service wirh ServiceLoader. I'm running it packaged with shadow jar into a plugin for a Minecraft server. Do you know what's necessary to have it loaded?

**Comment by Miclebrick** [comment]
fixed it with `System.setProperty("org.litote.mongo.test.mapping.service", "org.litote.kmongo.jackson.JacksonClassMappingTypeService")`

**Comment by bluefireoly** [comment]
> 
> 
> fixed it with `System.setProperty("org.litote.mongo.test.mapping.service", "org.litote.kmongo.jackson.JacksonClassMappingTypeService")`

Why is this the case with Minecraft / Spigot / Bukkit Plugins?

**Comment by MicleBrick** [comment]
I think it's because it loads the plugins from jar files, which screws up KMongo's automatic detection of the service class, thus requiring you to manually set it

**Comment by bluefireoly** [comment]
After reloading it gets even worse (and yes I know you should not reload):
`java.util.zip.ZipException:` ZipFile invalid LOC header (bad signature)`
Bukkit and reflections are never a good combination.

**Comment by enderian** [comment]
I know this issue is kind of dead, but it unfortunately it is still around 😅 

The problem lies with the `ServiceLoader` here, which attempts to load the serialisation strategy.
https://github.com/Litote/kmongo/blob/master/kmongo-shared/src/main/kotlin/org/litote/kmongo/service/ClassMappingType.kt#L23

This fails on Bukkit/Spigot environments, because the default `ClassLoader` does not have visibility into the resources of plugins loaded by the server, except only through the `PluginClassLoader`, which is provided upon initialisation.
A potential fix would be for KMongo to allow a user to somehow pass a `ClassLoader` to KMongo on initialisation, yet the hack als works

**Comment by zigzago** [comment]
Is it the same idea? -> https://gist.github.com/RezzedUp/d7957af10bfbfc6837ae1a4b55975f40

A PR would be appreciated ;)
